### ISSUE TITLE
Coding Convention

### ISSUE THREAD

**Issue by f-lab-stephen** [f-lab-edu/realtor#7]
## 목표

표준적인 Python coding convention인 [PEP 8](https://pep8.org/)을 준수하며 코딩하는 습관을 들이기 위해서입니다.

## 배경

Convention은 지키는 것이 서로의 코드를 볼 때 좋지만, 강제성이 없으면 지켜지지 않기 마련이므로, 일반적으로 협업 환경에서는 pre-commit hook을 각 개발자 머신에 설치해서 커밋 시도할 때 체크하는 툴을 사용하게 됩니다.

이를 위해서 Poetry를 통해 세 가지의 툴을 설치합니다.

1. `pre-commit`은 [Git pre-commit hook](https://git-scm.com/book/ko/v2/Git%EB%A7%9E%EC%B6%A4-Git-Hooks)을 설치하기 쉽게 도와주는 툴입니다. pre-commit hook 자체는 파이썬 도구가 아니라 Git에 내장된 도구라는 것은 알아 두세요.
2. [`black`](https://black.readthedocs.io/en/stable/) 은 PEP 8보다 엄격한 규칙을 정해 자동으로 포맷팅해 주기까지 하는 툴입니다. 블랙의 목표는 개발자가 어떻게 짜든지 나중에 똑같은 포맷으로 알아서 바꿔주겠다는 것입니다.
3. [`isort`](https://pycqa.github.io/isort/)는 임포트 순서를 자동으로 정렬해 주는 툴입니다. 당연히 [PEP 8에 임포트 순서가 정의](https://peps.python.org/pep-0008/#imports)되어 있습니다. 블랙에서 이 부분을 커버해 주지 않으므로 별도로 추가합니다.

## 태스크

- [ ] pre-commit 설정
  - 프로젝트 루트 디렉토리에서 `poetry add pre-commit isort black -G dev` 실행
  - [ ] `isort`, `black` 설정: 프로젝트 루트 디렉토리에 `.pre-commit-config.yaml`이라는 파일을 생성하고 아래와 같이 채워넣습니다.
    ```yaml
    # .pre-commit-config.yaml
    repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
      - id: isort
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
      - id: black
    ```
- [ ] 위에서 설정한 pre-commit 설치: 루트 디렉토리에서 `poetry install && poetry run pre-commit install` 실행
- [ ] black과 isort의 세부 설정: `pyproject.toml` 파일에서 디펜던시 부분 아래에 이렇게 추가합니다.
    ```toml
    # pyproject.toml
    # 윗 부분 생략...
    [tool.black]
    line-length = 119
    exclude = '''
    /(
      | \.git
      | \.pytype
      | migrations
    )/
    '''
    
    [tool.isort]
    line_length = 119
    profile = "black"
    skip_glob = ["*/migrations/*"]
    ```

## AC

- 설치 후 커밋을 시도해 보시면 커밋이 실패하면서 파일들이 자동으로 포맷팅이 된 것을 확인할 수 있습니다. 포맷팅된 커밋까지 포함해서 PR로 올려 주세요.
